name: MinGW Compatibility Checks
on:
  push:
    branches-ignore:
      - '**-coverage-report'
  pull_request:

jobs:
  run:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # At the moment only the latest version is supported by setup-mingw
        mingw-version: [ 7.3.0, 7.5.0, 8.1.0, 8.5.0, 9.4.0, 10.2.0, 10.3.0, 11.1.0, 11.2.0 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up MinGW-w64
        run: |
          choco install mingw --version ${{ matrix.mingw-version }} --force
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.17.x'
      - name: Build Tests
        run: |
          cmake . -G "MinGW Makefiles" -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++
          cmake --build . --target runPblTests
      - name: Run Tests
        run: |
          .\tests\runPblTests.exe
